services:
  postgres:
    image: postgres:16
    container_name: todo-postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: tododb
      POSTGRES_USER: todo
      POSTGRES_PASSWORD: todo
    volumes:
      - pgdata:/var/lib/postgresql/data
  backend:
    image: todo-backend:4
    container_name: todo-backend
    restart: unless-stopped
    environment:
      - DATABASE_URL=postgresql://todo:todo@postgres:5432/tododb
    depends_on:
      - postgres
  frontend:
    image: todo-frontend
    container_name: todo-frontend
    restart: unless-stopped
    ports:
      - "80:80"
    depends_on:
      - backend
volumes:
  pgdata:

